# Generated by Django 5.2.8 on 2026-04-23 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresetaudit'),
        ('tenants', '0001_multi_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('ADMIN', 'Administrator'), ('SECURITY_INCHARGE', 'Security In-Charge'), ('SECURITY_GUARD', 'Security Guard')], default='SECURITY_GUARD', max_length=24),
        ),
    ]
