# Generated by Django 5.2.8 on 2026-04-23 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('tenants', '0001_multi_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='tenants.tenant'),
        ),
    ]
